version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:20.15.1  # Updated to a more recent Node.js version

    working_directory: ~/hello-world-ci

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            npm install serverless --save-dev
            npm install

      # Authenticate with Docker
      - run:
          name: Docker login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

      # Run tests
      - run:
          name: Run tests with code coverage
          command: npm test --coverage

      # Deploy app
      - run:
          name: Deploy application
          command: |
            echo "SERVERLESS_ACCESS_KEY is set to: $SERVERLESS_ACCESS_KEY"
            export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
            export AWS_ACCESS_KEY_ID_KEY=$AWS_ACCESS_ID_KEY
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            
            npx serverless deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
